# Generated by Django 3.2.6 on 2022-05-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0007_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
