# Generated by Django 3.2.6 on 2022-05-24 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_delete_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
