# Generated by Django 3.2.6 on 2022-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
