# Generated by Django 3.2.6 on 2022-05-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_alter_paragraph_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
