# Generated by Django 3.2.6 on 2022-05-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_rakemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
