# Generated by Django 3.2.6 on 2022-04-25 15:46

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliceNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body_html', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('image_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=5000, null=True)),
                ('attribution', models.CharField(blank=True, max_length=5000, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
