# Generated by Django 3.2.6 on 2022-04-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slicenews',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
