# Generated by Django 3.2.6 on 2022-04-27 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_slicenews_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSN_URL',
            fields=[
                ('url', models.URLField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
