# Generated by Django 3.2.6 on 2022-04-28 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_msn_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MSN_URL',
        ),
    ]
