# Generated by Django 3.2.6 on 2022-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220428_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenews',
            name='content',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
