# Generated by Django 3.2.6 on 2022-04-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_articlenews_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlenews',
            options={'ordering': ['publish_date']},
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='content',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
