# Generated by Django 3.2.6 on 2022-05-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220430_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slicenews',
            options={'ordering': ['publish_date']},
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
