# Generated by Django 3.2.6 on 2022-05-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220502_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenews',
            name='content',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
