# Generated by Django 3.2.6 on 2022-05-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
