# Generated by Django 3.2.6 on 2022-01-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_word', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
