# Generated by Django 3.2.6 on 2022-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggtrends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('exploreLink', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
