# Generated by Django 3.2.6 on 2022-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggtrends', '0002_yeartrend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeartrend',
            old_name='index',
            new_name='year_trend',
        ),
        migrations.RemoveField(
            model_name='yeartrend',
            name='exploreLink',
        ),
        migrations.RemoveField(
            model_name='yeartrend',
            name='title',
        ),
        migrations.RemoveField(
            model_name='yeartrend',
            name='year',
        ),
        migrations.AddField(
            model_name='yeartrend',
            name='trends',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
