# Generated by Django 3.2.6 on 2022-03-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggtrends', '0003_auto_20220320_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleWord',
        ),
    ]
