# Generated by Django 3.2.6 on 2022-03-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggtrends', '0005_auto_20220320_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaytrends',
            name='trendpost',
        ),
        migrations.AlterField(
            model_name='trendposts',
            name='trend_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ggtrends.todaytrends'),
        ),
    ]
