# Generated by Django 3.2.6 on 2022-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggtrends', '0007_alter_trendposts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendposts',
            name='body',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
