# Generated by Django 3.2.6 on 2022-05-02 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VietNamMusicVideo',
            fields=[
                ('pos', models.IntegerField(default=0)),
                ('vid_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vid_link', models.URLField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VietNamTrendVideo',
            fields=[
                ('pos', models.IntegerField(default=0)),
                ('vid_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vid_link', models.URLField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
