# Generated by Django 3.2.6 on 2022-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vietnammusicvideo',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='vietnamtrendvideo',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='vietnammusicvideo',
            name='embed_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vietnamtrendvideo',
            name='embed_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
