# Generated by Django 3.2.6 on 2022-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20220502_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vietnammusicvideo',
            name='embed_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vietnamtrendvideo',
            name='embed_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
