# Generated by Django 3.2.6 on 2022-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cursor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='page_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
