# Generated by Django 3.2.6 on 2022-04-05 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('title', models.CharField(blank=True, max_length=50000, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.CharField(blank=True, max_length=50000, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=50000, null=True)),
                ('content', models.CharField(blank=True, max_length=1000000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
