# Generated by Django 3.2.6 on 2022-05-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longesttrend',
            options={'ordering': ['trend_name']},
        ),
        migrations.AlterModelOptions(
            name='tophashtagtrend',
            options={'ordering': ['trend_name']},
        ),
        migrations.AlterModelOptions(
            name='vietnamtwittertrend',
            options={'ordering': ['trend_name']},
        ),
        migrations.AlterModelOptions(
            name='worldwidetwittertrend',
            options={'ordering': ['created']},
        ),
    ]
