# Generated by Django 3.2.6 on 2022-06-16 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ggtrends', '0002_auto_20220522_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendHotPosts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=50000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('trend_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ggtrends.todaytrends')),
            ],
        ),
    ]
